export const POST_CATEGORIES = [
  { value: "GENERAL", label: "General" },
  { value: "ENTERTAINMENT", label: "Entertainment" },
  { value: "TECHNOLOGY", label: "Technology" },
  { value: "ARTIFICIAL_INTELLIGENCE", label: "Artificial Intelligence" },
  { value: "GAMING", label: "Gaming" },
  { value: "SCIENCE", label: "Science" },
  { value: "EDUCATION", label: "Education" },
  { value: "BUSINESS", label: "Business" },
  { value: "FINANCE", label: "Finance" },
  { value: "PERSONAL_FINANCE", label: "Personal Finance" },
  { value: "POLITICS", label: "Politics" },
  { value: "GEOPOLITICS", label: "Geopolitics" },
  { value: "NEWS", label: "News & Current Affairs" },
  { value: "SPORTS", label: "Sports" },
  { value: "LIFESTYLE", label: "Lifestyle" },
  { value: "HEALTH_AND_FITNESS", label: "Health & Fitness" },
  { value: "TRAVEL", label: "Travel" },
  { value: "FOOD", label: "Food" },
  { value: "FASHION", label: "Fashion" },
  { value: "BEAUTY", label: "Beauty" },
  { value: "MUSIC", label: "Music" },
  { value: "CULTURE_AND_ARTS", label: "Culture & Arts" },
  { value: "CAREER", label: "Career & Jobs" },
  { value: "DESIGN", label: "Design" },
  { value: "ENVIRONMENT", label: "Environment & Nature" },
  { value: "DIY_AND_CRAFT", label: "DIY & Craft" },
  { value: "PARENTING", label: "Parenting" },
  { value: "CASE_STUDIES", label: "Case Studies" },
] as const;

export type PostCategory =
  (typeof POST_CATEGORIES)[number]["value"];